language: node_js
node_js:
  - lts/*
before_install:
install:
  - npm install
jobs:
  include:
    - stage: docs
      if: branch = master
      script: npm run docs:build
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: docs/.vuepress/dist/Mars
        github_token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
        keep_history: true
        on:
          branch: master
    - stage: release
      if: branch = release
      script: git checkout master
      before_deploy:
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        - git remote set-url origin https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
      deploy:
        provider: script
        script:
          - npm run version && npm run publish -- --yes
        on:
          branch: release
